name: fish_feeds_app
description: "A new Flutter project."


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

#------[PACKAGES]------
dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  get: ^4.7.2
  iconsax: ^0.0.8
  lottie: ^3.3.1
  smooth_page_indicator: ^1.2.1
cupertino_icons: ^1.0.8


# UTILITIES

#-------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true


#---------[ASSETS]----------
  assets:
    - assets/logo/
    - assets/animations/
    - assets/images/


#-------[FONTS]--------
fonts:
  - family: 'Nunito'
    fonts:
      - asset: assets/fonts/Nunito-Light.ttf
        weight: 300
      - asset: assets/fonts/Nunito-Regular.ttf
        weight: 400
      - asset: assets/fonts/Nunito-Regular.ttf
        weight: italic
      - asset: assets/fonts/Nunito-Medium.ttf
        weight: 500
      - asset: assets/fonts/Nunito-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Nunito-Bold.ttf
        weight: 800





  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
